# Generated by Django 5.0.14 on 2026-07-15 07:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_price_usdt', models.DecimalField(decimal_places=6, default=Decimal('0.10'), max_digits=18)),
                ('ticket_threshold', models.PositiveIntegerField(default=100)),
                ('jackpot_bps', models.PositiveIntegerField(default=7000)),
                ('rollover_bps', models.PositiveIntegerField(default=2000)),
                ('fee_bps', models.PositiveIntegerField(default=1000)),
                ('min_withdraw_usdt', models.DecimalField(decimal_places=6, default=Decimal('5'), max_digits=18)),
                ('kyc_threshold_usdt', models.DecimalField(decimal_places=6, default=Decimal('100'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='JackpotPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jackpot_usdt', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('rollover_usdt', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('fee_usdt', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('kyc_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=16)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, help_text='ISO-3166 alpha-2, captured at signup', max_length=2)),
                ('self_excluded_until', models.DateTimeField(blank=True, null=True)),
                ('weekly_deposit_cap_usdt', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('old_value', models.CharField(max_length=256)),
                ('new_value', models.CharField(max_length=256)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=128, unique=True)),
                ('derivation_index', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_swept_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(help_text='ET calendar date this drawing is for', unique=True)),
                ('status', models.CharField(choices=[('committed', 'Seed committed'), ('snapshot', 'Tickets snapshotted'), ('drawn', 'Drawn'), ('paid', 'Paid out'), ('void', 'Void (no tickets)')], default='committed', max_length=16)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('server_seed', models.CharField(blank=True, max_length=64)),
                ('snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('total_tickets', models.PositiveBigIntegerField(default=0)),
                ('beacon_slot', models.BigIntegerField(blank=True, null=True)),
                ('beacon_blockhash', models.CharField(blank=True, max_length=128)),
                ('winning_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('jackpot_usdt', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('payout_tx', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshotted_at', models.DateTimeField(blank=True, null=True)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='SelfExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_exclusions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=128, unique=True)),
                ('chain', models.CharField(default='solana', max_length=32)),
                ('provider', models.CharField(choices=[('phantom', 'Phantom'), ('solflare', 'Solflare'), ('trust_wallet', 'Trust Wallet'), ('metamask', 'MetaMask'), ('walletconnect', 'WalletConnect')], max_length=32)),
                ('nonce', models.CharField(blank=True, max_length=64)),
                ('nonce_created_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('amount_usdt', models.DecimalField(decimal_places=6, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('kyc_required', 'KYC required'), ('approved', 'Approved'), ('sent', 'Sent'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('tx_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('buy_ball', 'Buy $BALL'), ('win', 'Draw win'), ('withdraw', 'Withdrawal'), ('fee', 'Platform fee'), ('refund', 'Refund'), ('adjustment', 'Manual adjustment')], max_length=16)),
                ('usdt_delta', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('ball_delta', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('ref', models.CharField(blank=True, help_text='e.g. draw id, withdrawal id, tx hash', max_length=128)),
                ('tx_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'entry_type'], name='core_ledger_user_id_a9d9d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_balance', models.DecimalField(decimal_places=6, max_digits=18)),
                ('ticket_start', models.PositiveBigIntegerField()),
                ('ticket_end', models.PositiveBigIntegerField()),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ticket_start'],
                'unique_together': {('draw', 'user')},
            },
        ),
    ]
