# Generated by Django 5.0.14 on 2026-07-15 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='payout_id',
            field=models.CharField(blank=True, help_text='NowPayments payout batch id', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='usdt_trc20_payout_address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_id',
            field=models.CharField(blank=True, help_text='NowPayments payout batch id', max_length=64),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pay_address', models.CharField(blank=True, max_length=128)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('price_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for payment'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially paid'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='waiting', max_length=16)),
                ('tx_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DepositAddress',
        ),
    ]
