# Generated by Django 5.0.14 on 2026-07-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_draw_payout_id_user_usdt_trc20_payout_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletlink',
            name='provider',
            field=models.CharField(choices=[('phantom', 'Phantom'), ('solflare', 'Solflare'), ('trust_wallet', 'Trust Wallet'), ('metamask', 'MetaMask'), ('tronlink', 'TronLink'), ('walletconnect', 'WalletConnect')], max_length=32),
        ),
    ]
