# Generated by Django 5.0.14 on 2026-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_walletlink_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deposit',
            name='order_id',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
