# Generated by Django 5.0.14 on 2026-07-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deposit_invoice_url_deposit_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='manual_deposit_address',
            field=models.CharField(blank=True, help_text='USDT-TRC20 address shown for manual deposits (admin-reviewed instead of NowPayments).', max_length=128),
        ),
        migrations.AddField(
            model_name='deposit',
            name='method',
            field=models.CharField(choices=[('nowpayments', 'NowPayments'), ('manual', 'Manual USDT-TRC20')], default='nowpayments', max_length=16),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for payment'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('sending', 'Sending'), ('partially_paid', 'Partially paid'), ('pending_review', 'Pending admin review'), ('finished', 'Finished'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='waiting', max_length=16),
        ),
    ]
