# Generated by Django 6.0.1 on 2026-06-13 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(db_index=True, unique=True)),
                ('opens_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('draws_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('drawn', 'Drawn')], default='open', max_length=8)),
                ('winning_numbers', models.JSONField(blank=True, null=True)),
                ('jackpot_fudsx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
            ],
            options={
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=64, unique=True)),
                ('referral_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('referral_earnings_fudsx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='lottery.account')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fudsx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('txid', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_generated', to='lottery.account')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_received', to='lottery.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField()),
                ('txid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('paid_fudsx', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('matched', models.PositiveSmallIntegerField(default=0)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lottery.account')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lottery.round')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
